home_phone:   +61 3 9628 3624
mobile_phone: +61 422 082 738

references:
  - mark:
      projects:   ["Melbourne IT AWS Migration \\ \"DevOps\""]
      roles:      ["Manager, Digital"]
      first_name: Mark
      last_name:  Murphy
      phone:      +61 3 8624 2378
      email:      mark.murphy@melbourneit.com.au

skills:
  max:        10
  extra:
   - technical: [Solution Design & Architecture, REST, APIs, AWS, Puppet, Automation]
   - languages: [Java, PHP, Ruby, Scala]

other:
  interests: [The Internet, Human Computer Interaction & Usability, Basketball, Waterskiing\Wakeboarding, Snowboarding]

projects:
  - "Melbourne IT AWS Migration \\ \"DevOps\"": "Melbourne IT"
  - "Melbourne IT Website Refresh (In Progress)": "Melbourne IT"
  - "Startup - Mobile App (Advertising)": "Freelance"
  - "Transformation": "Melbourne IT"
  - "Renewal - Conversion Rate Optimisation": "Melbourne IT"
  - "Skylock - Cloud-based GPS Security Portal": "Freelance"
  - "Substantiate - GPS logbook solutions": "Freelance"
  - "Auto-renewal": "Melbourne IT"
  - "Business Transformation Programme (IWS)": "Melbourne IT"